### ISSUE TITLE
Imprison blitz triggers the anticheat

### ISSUE THREAD

**Issue by Idealosu** [HardstylesDev/BlitzSG#4]
Due to how Imprison simply inflicts players with Slowness X, it can be completely bypassed by sprint jumping. However, this also happens to get flagged by the anticheat for speed/sprint hacks, thus resulting in false bans. Can be reproduced by using the blitz and having someone sprint jump, then checking logs.

**Comment by HardstylesDev** [comment]
Solved as of today

[screenshot](https://i.theblitzbot.com/a2fTU.png)
